"""Ports required by application use cases."""

from typing import Protocol

from backend.domain.models.session import SessionData


class SessionRepository(Protocol):
    async def create(self, data: SessionData) -> str: ...
    async def get(self, session_id: str) -> SessionData | None: ...
    async def delete(self, session_id: str) -> None: ...
    async def close(self) -> None: ...
