traefik:
  install: true
  bundledIngressClass: traefik-int
  externalIngressClass: traefik
  serviceType: LoadBalancer

backendIngress:
  enabled: true

images:
  backend: {repository: support-ticket-portal/backend, tag: int, pullPolicy: Always}
  frontend: {repository: support-ticket-portal/frontend, tag: int, pullPolicy: Always}
  otelCollector: {repository: otel/opentelemetry-collector-contrib, tag: latest, pullPolicy: Always}
  alloy: {repository: grafana/alloy, tag: latest, pullPolicy: Always}
blueGreen:
  activeSlot: blue
  slots:
    blue: {backendTag: int, frontendTag: int}
    green: {backendTag: int, frontendTag: int}
app:
  sessionCookieSecure: false
  backendEnv: {DEPLOY_ENVIRONMENT: int}
  testUsers:
    enabled: true
